//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24DH11420_LTTH_BE234.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
